name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - id: get-version
      name: Get version for tag
      uses: actions/github-script@v3
      with:
        script: |
          const version = context.ref.substr(10);
          const sha = context.sha.substr(0, 10);
          core.setOutput('version', `${version}+${sha}`);

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        sed -i -E s/"(const version = )'(.*)';"/"\1'${{ steps.get-version.outputs.version }}';"/g src/environments/environment.prod.ts
        npm run ng -- deploy
