name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - id: get-version
      name: Get version for tag
      uses: actions/github-script@v3
      with:
        script: |
          const version = github.ref.substr(10);
          core.setOutput('version', version);

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        sed -i -E s/"(\"version\": )\"(.*)\"\,"/"\1\"${{ steps.get-version.outputs.version }}\"\,"/g package.json
        npm run ng -- deploy
